spring.application.name=ev
spring.jackson.deserialization.fail-on-unknown-properties=true
server.port=8080

# JWT
jwt.secret=CHANGE_THIS_TO_A_LONG_RANDOM_SECRET_KEY
jwt.access-token-expiration=900000
jwt.refresh-token-expiration=2592000000